language: python
python: 
  - "3.6"
services:
  - postgresql
env:
  - DJANGO=2.0 DB=postgres
install:
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv install
before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
  - pipenv run python manage.py migrate
script:
  - pipenv run python manage.py test
