language: python
    python: 
      - "3.6"
    services:
      - postgresql
    env:
      -DJANGO=2.0 DB=postgres
    install:
      - pip install -r requirements.txt
    before_script:
      - psql -c "CREATE DATABASE mydb;" -U postgres
      - python manage.py migrate
    script:
      - python manage.py test