# Generated by Django 2.0.7 on 2018-07-05 10:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.generic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('billing_id', models.CharField(blank=True, max_length=50, verbose_name='billing id')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('zip_code', models.CharField(max_length=50, verbose_name='zip code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('vat_id', models.CharField(blank=True, max_length=50, verbose_name='vat id')),
                ('bic', localflavor.generic.models.BICField(blank=True, max_length=11)),
                ('iban', localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=34, use_nordea_extensions=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('billing_id', models.CharField(blank=True, max_length=50, verbose_name='billing id')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('zip_code', models.CharField(max_length=50, verbose_name='zip code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('vat_id', models.CharField(blank=True, max_length=50, verbose_name='vat id')),
                ('internal_notes', models.TextField(blank=True, verbose_name='description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssuedInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('billing_id', models.CharField(blank=True, max_length=50, verbose_name='billing id')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('zip_code', models.CharField(max_length=50, verbose_name='zip code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('vat_id', models.CharField(blank=True, max_length=50, verbose_name='vat id')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('series', models.CharField(max_length=20, verbose_name='series')),
                ('number', models.PositiveIntegerField(editable=False, verbose_name='number')),
                ('irpf_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='irpf rate')),
                ('net', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='net')),
                ('vat', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='vat')),
                ('irpf', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='irpf')),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='amount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='bills.Client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedInvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=300, verbose_name='concept')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave it blank for auto-calculate', max_digits=10, verbose_name='unit_price')),
                ('net', models.DecimalField(blank=True, decimal_places=2, help_text='Leave it blank for auto-calculate', max_digits=10, verbose_name='net')),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='vat rate')),
                ('vat', models.DecimalField(blank=True, decimal_places=2, help_text='Leave it blank for auto-calculate', max_digits=10, verbose_name='vat')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave it blank for auto-calculate', max_digits=10, verbose_name='amount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bills.IssuedInvoice')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='issuedinvoice',
            unique_together={('series', 'number')},
        ),
    ]
